root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"

bin = "tmp/main"

full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 8000"

include_ext = ["go", "tpl", "tmpl", "html"]

exclude_dir = ["assets", "tmp", "vendor"]

include_dir = []

exclude_file = []

exclude_regex = ["_test.go"]

exclude_unchanged = true

follow_symlink = true

log = "air.log"

delay = 1000

stop_on_error = false

kill_delay = 500

[log]
time = false

[color]
main = "magenta" 
watcher = "cyan" 
build = "yellow" 
runner = "green"
error = "red"
success = "blue"

# 終了時に一時ファイルをクリーンアップする
[misc]
clean_on_exit = true