linters:
  disable-all: true
  enable:
    - goimports
    - deadcode
    - errcheck
    - gocognit
    - gocritic
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace

linters-settings:
  govet:
    check-shadowing: false

  gocycle:
    min-complexity: false

  misspell:
    locale: US